# Generated by Django 4.0 on 2021-12-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20211220_15-21-54', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20211220_15-21-54', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='telegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('mfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.mfostruct')),
            ],
        ),
    ]
