# Generated by Django 3.2.10 on 2021-12-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_atmimage_title_alter_atmmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20211220_16-30-45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20211220_16-30-45', verbose_name='Изображение'),
        ),
    ]
