# Generated by Django 4.0 on 2021-12-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_atmimage_title_alter_atmmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atm',
            options={'verbose_name': 'Банкомат', 'verbose_name_plural': 'Банкоматы'},
        ),
        migrations.AlterModelOptions(
            name='atmimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='atmmodel',
            options={'verbose_name': 'Модель ATM', 'verbose_name_plural': 'Модели ATM'},
        ),
        migrations.AlterModelOptions(
            name='atmmodelfunction',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AlterModelOptions(
            name='mfostruct',
            options={'verbose_name': 'MFO', 'verbose_name_plural': 'MFO'},
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20211222_12-11-37', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20211222_12-11-37', verbose_name='Изображение'),
        ),
    ]
