# Generated by Django 4.0 on 2021-12-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_atm_options_alter_atmimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20211222_12-31-25', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20211222_12-31-25', verbose_name='Изображение'),
        ),
    ]
