# Generated by Django 3.2.10 on 2021-12-23 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_auto_20211220_1630'),
        ('crudapp', '0007_alter_atmimage_title_alter_atmmodel_image'),
    ]

    operations = [
    ]
