# Generated by Django 3.2.10 on 2021-12-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0019_auto_20211229_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20211229_10-02-17', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20211229_10-02-17', verbose_name='Изображение'),
        ),
    ]
