# Generated by Django 3.2.10 on 2022-01-06 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0021_auto_20220105_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrammsg',
            old_name='text',
            new_name='json',
        ),
        migrations.RenameField(
            model_name='telegrammsg',
            old_name='ticketId',
            new_name='t',
        ),
        migrations.RemoveField(
            model_name='telegrammsg',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='telegrammsg',
            name='date',
        ),
        migrations.RemoveField(
            model_name='telegrammsg',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='telegrammsg',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='closed',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='date',
        ),
        migrations.AddField(
            model_name='mfostruct',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='МФО'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='atmId',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='crudapp.atm'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dataClosed',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='closed'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dataCreated',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='opened'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='operator',
            field=models.TextField(blank=True, default='', null=True, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220106_11-12-42', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220106_11-12-42', verbose_name='Изображение'),
        ),
    ]
