# Generated by Django 3.2.10 on 2022-01-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0023_auto_20220106_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='atmId',
            new_name='atm',
        ),
        migrations.AddField(
            model_name='ticket',
            name='uid',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.CASCADE, to='crudapp.telegramuser'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220106_11-24-46', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220106_11-24-46', verbose_name='Изображение'),
        ),
    ]
