# Generated by Django 3.2.10 on 2022-01-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0025_auto_20220106_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='merchantId',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Merchant ID'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220106_11-41-23', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220106_11-41-23', verbose_name='Изображение'),
        ),
    ]
