# Generated by Django 3.2.10 on 2022-01-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0032_auto_20220106_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220107_17-23-56', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220107_17-23-56', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='atm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crudapp.atm'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crudapp.telegramuser'),
        ),
    ]
