# Generated by Django 3.2.10 on 2022-01-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0035_auto_20220107_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220107_18-04-37', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220107_18-04-37', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='broken',
            field=models.ManyToManyField(blank=True, to='crudapp.brokenCategory', verbose_name='Проблема'),
        ),
    ]
