# Generated by Django 3.2.10 on 2022-01-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0037_auto_20220108_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='edited',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='edited'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220108_13-46-19', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220108_13-46-19', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(blank=True, null=True, verbose_name='status'),
        ),
    ]
