# Generated by Django 3.2.10 on 2022-01-08 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0040_auto_20220108_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220108_15-02-20', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220108_15-02-20', verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='broken',
        ),
        migrations.AddField(
            model_name='ticket',
            name='broken',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crudapp.brokencategory', verbose_name='Проблема'),
        ),
    ]
