# Generated by Django 3.2.10 on 2022-01-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0048_auto_20220113_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='serialNumber',
            field=models.PositiveBigIntegerField(verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220113_11-42-15', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220113_11-42-15', verbose_name='Изображение'),
        ),
    ]
