# Generated by Django 3.2.10 on 2022-01-17 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0049_auto_20220113_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCIPTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_name', models.TextField(blank=True, default='', null=True)),
                ('model_name', models.TextField(blank=True, default='', null=True)),
                ('hardware_number', models.TextField(blank=True, default='', null=True)),
                ('firmware_number', models.TextField(blank=True, default='', null=True)),
                ('application_number', models.TextField(blank=True, default='', null=True)),
                ('approval_number', models.TextField(blank=True, default='', null=True)),
                ('version', models.TextField(blank=True, default='', null=True)),
                ('approval_class', models.TextField(blank=True, default='', null=True)),
                ('product_type', models.TextField(blank=True, default='', null=True)),
                ('expiry_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('approval_class_1', models.TextField(blank=True, default='', null=True)),
                ('pin_support', models.TextField(blank=True, default='', null=True)),
                ('pin_key_management', models.TextField(blank=True, default='', null=True)),
                ('sred_key_management', models.TextField(blank=True, default='', null=True)),
                ('prompt_control', models.TextField(blank=True, default='', null=True)),
                ('pin_entry_technology', models.TextField(blank=True, default='', null=True)),
                ('functions_provided', models.TextField(blank=True, default='', null=True)),
                ('not_marketed', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220117_09-29-56', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220117_09-29-56', verbose_name='Изображение'),
        ),
    ]
