# Generated by Django 3.2.10 on 2022-01-17 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0052_auto_20220117_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammsg',
            name='category',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='telegrammsg',
            name='download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammsg',
            name='dt',
            field=models.TextField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220117_12-24-36', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220117_12-24-36', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pcipts',
            name='approval_class',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='pcipts',
            name='manufacturer_name',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='pcipts',
            name='show',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Показывать на сайте?'),
        ),
    ]
