# Generated by Django 3.2.10 on 2022-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0053_auto_20220117_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220117_15-15-22', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220117_15-15-22', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'open'), (1, 'closed'), (2, 'cancel'), (3, 'service'), (4, 'panding'), (5, 'unknown')], default=5, null=True, verbose_name='status'),
        ),
    ]
