# Generated by Django 3.2.10 on 2022-01-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0055_auto_20220117_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammsg',
            name='operator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegrammsg',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220118_11-55-21', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220118_11-55-21', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'open'), (1, 'closed'), (2, 'cancel'), (3, 'service'), (4, 'pending'), (5, 'unknown')], default=5, null=True, verbose_name='status'),
        ),
    ]
