# Generated by Django 3.2.10 on 2022-01-18 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0056_auto_20220118_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammsg',
            name='path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220118_12-05-05', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220118_12-05-05', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='telegrammsg',
            name='dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
