# Generated by Django 3.2.10 on 2022-01-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0058_auto_20220125_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(default=0)),
                ('user', models.IntegerField(default=0)),
                ('message_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.IntegerField(choices=[(0, 'Узбекский'), (1, 'Русский')], default=0, verbose_name='Локализация'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220126_14-59-26', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220126_14-59-26', verbose_name='Изображение'),
        ),
    ]
