# Generated by Django 3.2.10 on 2022-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0059_auto_20220126_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220126_17-34-40', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220126_17-34-40', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='chat',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='message_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='user',
            field=models.BigIntegerField(default=0),
        ),
    ]
