# Generated by Django 3.2.10 on 2022-01-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0066_auto_20220127_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220127_14-38-29', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220127_14-38-29', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataClosed',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Закрыт'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dataCreated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создан'),
        ),
    ]
