# Generated by Django 3.2.10 on 2022-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0068_auto_20220127_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='updated',
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220127_14-41-45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220127_14-41-45', verbose_name='Изображение'),
        ),
    ]
