# Generated by Django 3.2.10 on 2022-01-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0074_auto_20220127_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammsg',
            name='caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='telegrammsg',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220128_10-12-42', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220128_10-12-42', verbose_name='Изображение'),
        ),
    ]
