# Generated by Django 3.2.10 on 2022-01-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0075_auto_20220128_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220128_12-22-38', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220128_12-22-38', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='telegrammsg',
            name='caption',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegrammsg',
            name='text',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
