# Generated by Django 3.2.10 on 2022-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0076_auto_20220128_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='inBankProcessing',
            field=models.BooleanField(default=False, verbose_name='Процессинговый центр'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220131_15-49-45', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220131_15-49-45', verbose_name='Изображение'),
        ),
    ]
