# Generated by Django 3.2.10 on 2022-02-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0078_auto_20220131_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='NFC',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0, verbose_name='NFC'),
        ),
        migrations.AddField(
            model_name='atm',
            name='RDSCommander',
            field=models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0, verbose_name='RDS Commander'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220201_09-56-19', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220201_09-56-19', verbose_name='Изображение'),
        ),
    ]
