# Generated by Django 3.2.10 on 2022-02-04 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0082_auto_20220204_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Договор')),
                ('dataBegin', models.DateTimeField(verbose_name='Дата начала')),
                ('dataEnd', models.DateTimeField(verbose_name='Дата конца')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Компания')),
                ('type', models.IntegerField(choices=[(0, 'Гарантийное'), (1, 'Сервисное')], default=0, verbose_name='Вид')),
                ('amt', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
            ],
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220204_11-38-22', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220204_11-38-22', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='atm',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudapp.servicecontract', verbose_name='Обслуживание'),
        ),
    ]
