# Generated by Django 3.2.10 on 2022-02-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0090_auto_20220204_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220204_11-59-00', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220204_11-59-00', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='amt',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Договор'),
        ),
    ]
