# Generated by Django 3.2.10 on 2022-02-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0105_auto_20220207_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokencategory',
            options={'verbose_name': 'Категории поломок', 'verbose_name_plural': 'Категории поломок'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='servicecontract',
            options={'verbose_name': 'Сервис Компании', 'verbose_name_plural': 'Сервис Компании'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Телеграм Пользователи', 'verbose_name_plural': 'Телеграм Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Тикеты', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220209_09-16-20', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220209_09-16-20', verbose_name='Изображение'),
        ),
    ]
