# Generated by Django 3.2.10 on 2022-02-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0108_auto_20220209_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='workTime',
            field=models.CharField(blank=True, default='24/7', max_length=255, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220211_09-53-27', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220211_09-53-27', verbose_name='Изображение'),
        ),
    ]
