# Generated by Django 3.2.10 on 2022-02-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0109_auto_20220211_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atm',
            name='workTime',
            field=models.IntegerField(choices=[(0, '24/7'), (1, '09:00-18:00'), (2, '08:00-23:00'), (3, '08:00-01:00')], default=0, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='atmimage',
            name='title',
            field=models.CharField(default='atm_img_20220211_10-00-43', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='atmmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='model/model_img_20220211_10-00-43', verbose_name='Изображение'),
        ),
    ]
