# Generated by Django 3.2.10 on 2021-12-29 05:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegtseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MERCHANT', models.CharField(max_length=255, verbose_name='MERCHANT')),
                ('PARENT', models.CharField(blank=True, max_length=255, null=True, verbose_name='PARENT')),
                ('ABRV_NAME', models.CharField(blank=True, max_length=255, null=True, verbose_name='ABRV_NAME')),
                ('FULL_NAME', models.CharField(blank=True, max_length=255, null=True, verbose_name='FULL_NAME')),
                ('CNTRY', models.CharField(blank=True, max_length=255, null=True, verbose_name='CNTRY')),
                ('CITY', models.CharField(blank=True, max_length=255, null=True, verbose_name='CITY')),
                ('STREET', models.CharField(blank=True, max_length=255, null=True, verbose_name='STREET')),
                ('REG_NR', models.CharField(blank=True, max_length=255, null=True, verbose_name='REG_NR')),
                ('PHONE', models.CharField(blank=True, max_length=255, null=True, verbose_name='PHONE')),
                ('MCC', models.CharField(blank=True, max_length=255, null=True, verbose_name='MCC')),
                ('POST_IND', models.CharField(blank=True, max_length=255, null=True, verbose_name='POST_IND')),
                ('MRC_PHONE', models.CharField(blank=True, max_length=255, null=True, verbose_name='MRC_PHONE')),
                ('req', models.TextField(blank=True, null=True, verbose_name='req')),
                ('status', models.BooleanField(default=False, verbose_name='STATUS')),
                ('dt', models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 2, 26, 56657), verbose_name='dt')),
            ],
            options={
                'verbose_name': 'Regtse',
                'verbose_name_plural': 'Regtse',
            },
        ),
        migrations.CreateModel(
            name='RegtseDataTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MERCHANT', models.CharField(max_length=255, verbose_name='MERCHANT')),
                ('PARENT', models.CharField(max_length=255, verbose_name='PARENT')),
                ('ABRV_NAME', models.CharField(blank=True, max_length=255, null=True, verbose_name='ABRV_NAME')),
                ('FULL_NAME', models.CharField(blank=True, max_length=255, null=True, verbose_name='FULL_NAME')),
                ('CNTRY', models.CharField(blank=True, max_length=255, null=True, verbose_name='CNTRY')),
                ('CITY', models.CharField(blank=True, max_length=255, null=True, verbose_name='CITY')),
                ('STREET', models.CharField(blank=True, max_length=255, null=True, verbose_name='STREET')),
                ('REG_NR', models.CharField(blank=True, max_length=255, null=True, verbose_name='REG_NR')),
                ('PHONE', models.CharField(blank=True, max_length=255, null=True, verbose_name='PHONE')),
                ('MCC', models.CharField(blank=True, max_length=255, null=True, verbose_name='MCC')),
                ('POST_IND', models.CharField(blank=True, max_length=255, null=True, verbose_name='POST_IND')),
                ('MRC_PHONE', models.CharField(blank=True, max_length=255, null=True, verbose_name='MRC_PHONE')),
                ('req', models.TextField(blank=True, null=True, verbose_name='req')),
                ('status', models.BooleanField(default=False, verbose_name='STATUS')),
                ('dt', models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 2, 26, 58592), verbose_name='dt')),
            ],
            options={
                'verbose_name': 'Regtse Test',
                'verbose_name_plural': 'Regtse Test',
            },
        ),
        migrations.CreateModel(
            name='RequestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('method', models.TextField(blank=True, null=True, verbose_name='Метод')),
                ('scheme', models.TextField(blank=True, null=True, verbose_name='Схема')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Запрос')),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='API')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='RequestDataTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('method', models.TextField(blank=True, null=True, verbose_name='Метод')),
                ('scheme', models.TextField(blank=True, null=True, verbose_name='Схема')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('request', models.TextField(blank=True, null=True, verbose_name='Запрос')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='API')),
            ],
            options={
                'verbose_name': 'Файл (test)',
                'verbose_name_plural': 'Файлы (test)',
            },
        ),
        migrations.CreateModel(
            name='RegdevDataTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TERMINAL_ID', models.CharField(max_length=255, verbose_name='Terminal Id')),
                ('ACCEPTOR_ID', models.CharField(max_length=255, verbose_name='Acceptor Id')),
                ('TERM_TYPE', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('POINT_CODE', models.CharField(blank=True, max_length=255, null=True, verbose_name='Point Code')),
                ('SERIAL_NR', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number')),
                ('INV_NR', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inventory Number')),
                ('CURRENCY', models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency')),
                ('req', models.TextField(blank=True, null=True, verbose_name='req')),
                ('status', models.BooleanField(default=False, verbose_name='STATUS')),
                ('dt', models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 2, 26, 59207), verbose_name='dt')),
                ('regtseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regtseId', to='myapi.regtsedatatest')),
            ],
            options={
                'verbose_name': 'Regdev Test',
                'verbose_name_plural': 'Regdev Test',
            },
        ),
        migrations.CreateModel(
            name='RegdevData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TERMINAL_ID', models.CharField(max_length=255, verbose_name='Terminal Id')),
                ('ACCEPTOR_ID', models.CharField(max_length=255, verbose_name='Acceptor Id')),
                ('TERM_TYPE', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('POINT_CODE', models.CharField(blank=True, max_length=255, null=True, verbose_name='Point Code')),
                ('SERIAL_NR', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial Number')),
                ('INV_NR', models.CharField(blank=True, max_length=255, null=True, verbose_name='Inventory Number')),
                ('CURRENCY', models.CharField(blank=True, max_length=255, null=True, verbose_name='Currency')),
                ('req', models.TextField(blank=True, null=True, verbose_name='req')),
                ('status', models.BooleanField(default=False, verbose_name='STATUS')),
                ('dt', models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 2, 26, 57407), verbose_name='dt')),
                ('regtseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regtseId', to='myapi.regtsedata')),
            ],
            options={
                'verbose_name': 'Regdev',
                'verbose_name_plural': 'Regdev',
            },
        ),
    ]
