# Generated by Django 3.2.10 on 2021-12-29 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20211229_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestdatatest',
            options={'verbose_name': 'File (test)', 'verbose_name_plural': 'Files (test)'},
        ),
        migrations.AlterField(
            model_name='regdevdata',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 6, 18, 150536), verbose_name='dt'),
        ),
        migrations.AlterField(
            model_name='regdevdatatest',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 6, 18, 152281), verbose_name='dt'),
        ),
        migrations.AlterField(
            model_name='regtsedata',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 6, 18, 149807), verbose_name='dt'),
        ),
        migrations.AlterField(
            model_name='regtsedatatest',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 29, 10, 6, 18, 151681), verbose_name='dt'),
        ),
    ]
