# Generated by Django 3.2.10 on 2022-01-25 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0044_auto_20220118_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regdevdata',
            options={'verbose_name': 'Устройства', 'verbose_name_plural': 'Устройства'},
        ),
        migrations.AlterModelOptions(
            name='regdevdatatest',
            options={'verbose_name': 'Устройства (test)', 'verbose_name_plural': 'Устройства (test)'},
        ),
        migrations.AlterModelOptions(
            name='regtsedata',
            options={'verbose_name': 'Мерчанты', 'verbose_name_plural': 'Мерчанты'},
        ),
        migrations.AlterModelOptions(
            name='regtsedatatest',
            options={'verbose_name': 'Мерчанты (test)', 'verbose_name_plural': 'Мерчанты (test)'},
        ),
        migrations.AlterModelOptions(
            name='requestdata',
            options={'verbose_name': 'Запросы', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AlterModelOptions(
            name='requestdatatest',
            options={'verbose_name': 'Запросы (test)', 'verbose_name_plural': 'Запросы (test)'},
        ),
        migrations.AlterField(
            model_name='regdevdata',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 17, 47, 685523), verbose_name='dt'),
        ),
        migrations.AlterField(
            model_name='regdevdatatest',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 17, 47, 687385), verbose_name='dt'),
        ),
        migrations.AlterField(
            model_name='regtsedata',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 17, 47, 684873), verbose_name='dt'),
        ),
        migrations.AlterField(
            model_name='regtsedatatest',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 25, 10, 17, 47, 686767), verbose_name='dt'),
        ),
    ]
